from tkinter import*
def clear_all():
    principle_field.delete(0,END)
    rate_field.delete(0,END)
    time_field.delete(0,END)
    compound_field.delete(0,END)
    principle_field.focus_set()
def calculate_ci():
    principle=int(principle_field.get())
    rate=int(rate_field.get())
    time=int(time_field.get())
    ci=principle*(pow((1+rate/100),time))
    compound_field.insert(10,ci)
if __name__=="__main__":
    gui=Tk()
    gui.configure(background="light green")
    gui.title("command Insert calculator")
    gui.geometry("400x250")
    label1=Label(gui,text="Principal Amount(RS)",fg='black',bg='white')
    label2=Label(gui,text="Rate(%)",fg='black',bg='white')
    label3=Label(gui,text="Time(year)",fg='black',bg='white')
    label4=Label(gui,text="Amount with compound interest",fg='black',bg='white')
    label1.grid(row=1,column=0,padx=10,pady=10)
    label2.grid(row=2,column=0,padx=10,pady=10)
    label3.grid(row=3,column=0,padx=10,pady=10)
    label4.grid(row=5,column=0,padx=10,pady=10)
    principle_field=Entry(gui)
    rate_field=Entry(gui)
    time_field=Entry(gui)
    compound_field=Entry(gui)
    principle_field.grid(row=1,column=1,padx=10,pady=10)
    rate_field.grid(row=2,column=1,padx=10,pady=10)
    time_field.grid(row=3,column=1,padx=10,pady=10)
    compound_field.grid(row=5,column=1,padx=10,pady=10)
    button1=Button(gui,text='submit',fg='black',bg='white',command=calculate_ci)
    button2=Button(gui,text='clear',fg='black',bg='white',command=clear_all)
    button1.grid(row=4,column=1,pady=10)
    button2.grid(row=6,column=1,pady=10)
    gui.mainloop()

